name: DevSecOps Pipeline

on:
  push:
    branches:
      - main

jobs:
  sast_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.8

      - name: Install Bandit
        run: pip install bandit

      - name: Run Bandit Scan
        run: bandit -r . -f json -o bandit_report.json

      - name: Upload Bandit Report
        uses: actions/upload-artifact@v2
        with:
          name: Bandit Report
          path: bandit_report.json
